Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_check_update = false
  config.vm.hostname = "docker-client01"
  config.vm.network "private_network", ip: "192.168.56.4"
  config.vm.provider "virtualbox" do |vb|
     #Virtual Machine name
     vb.name = "DockerClient1"
     # Display the VirtualBox GUI when booting the machine
     vb.gui = false
     # Customize the amount of memory on the VM:
     vb.memory = "1024"
   end
  config.vm.provision "shell", path: "install.sh"
end
