Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.provider :virtualbox do |vb|
    vb.name = "DockerEngine"
  end
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.56.2"
  config.vm.hostname = "dockerd"
  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = false
     # Customize the amount of memory on the VM:
     vb.memory = "2048"
   end
  config.vm.provision "shell", path: "install.sh"
end
